config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
  }
  ActiveAdmin.routes(self)
  resources :articles
  #devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get 'about', to: 'album#about'
  get 'news', to: 'articles#index'
  get 'cooking', to: 'articles#index'
  get 'roastering', to: 'articles#index'
  get 'other', to: 'articles#index'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "articles#index"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, Article
    cannot :read, Article, published_at:nil

    return unless user.present?  # additional permissions for logged in users (they can read their own posts)

    can :create, Article
    can :read, Article, author_id: user.id
    can :edit, Article, author_id: user.id, published_at: nil
    can :delete, Article, author_id: user.id, published_at: nil

    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "encrypted_password", "id", "id_value", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  extend FriendlyId

  has_rich_text :body
  has_one_attached :preview_image
  belongs_to :author, class_name: 'User', foreign_key: :author_id

  friendly_id :title, use: :slugged

  def should_generate_new_friendly_id?
    slug.blank? || title_changed?
  end

  validates :title, presence: true
  validates :body, presence: true
  validates :preview_image, presence: true
  def self.ransackable_associations(auth_object = nil)
    ["author", "preview_image_attachment", "preview_image_blob", "rich_text_body"]
  end
  def self.ransackable_attributes(auth_object = nil)
    ["author_id", "body", "created_at", "id", "id_value", "published_at", "title", "updated_at"]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]


  has_many :articles, foreign_key: :author_id

  def self.ransackable_associations(auth_object = nil)
    ["articles"]
  end
  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "encrypted_password", "id", "id_value", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.nickname = auth.info.name
      user.image = auth.info.image
    end

    user = find_by(provider: auth.provider, uid: auth.uid)

    user.first_name = auth.info.first_name
    user.last_name = auth.info.last_name
    user.nickname = auth.info.name
    user.image = auth.info.image

    user.save
    user
  end
end

app/controllers/album_controller.rb
class AlbumController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    @articles = Article.accessible_by(current_ability).order(id: :desc)
  end

  # GET /articles/1 or /articles/1.json
  def show
    authorize! :read, @article
  end

  # GET /articles/new
  def new
    @article = Article.new
    authorize! :create, @article
  end

  # GET /articles/1/edit
  def edit
    authorize! :edit, @article
  end

  # POST /articles or /articles.json
  def create
    @article = current_user.articles.build(article_params)
    authorize! :create, @article

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    authorize! :delete, @article

    @article.destroy!

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :body, :preview_image, :published_at)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    user = User.from_omniauth(auth)
    if user.present?
      sign_out_all_scopes
      flash[:success] = t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect user, event: :authentication
    else
      flash[:alert] =
        t 'devise.omniauth_callbacks.failure', kind: 'Google', reason: "#{auth.info.email} is not authorized."
      redirect_to new_user_session_path
    end
  end
  protected
  def after_omniauth_failure_path_for(_scope)
    new_user_session_path
  end
  def after_sign_in_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || root_path
  end
  private
  def auth
    @auth ||= request.env['omniauth.auth']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/header_helper.rb
module HeaderHelper
  def current_link_class(path)
    current_page?(path) ? 'nav-link px-2 link-secondary' : 'nav-link px-2 link-body-emphasis'
  end

  def root_link_class(path)
    (current_page?(path) || current_page?('')) ? 'nav-link px-2 link-secondary' : 'nav-link px-2 link-body-emphasis'
  end
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/album/about.html.erb
<section class="py-5 text-center container">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <h1 class="fw-light">About me!</h1>
    </div>
  </div>
</section>

app/views/album/index.html.erb
<main>

  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light"><%= t('welcome.title') %></h1>
        <p class="lead text-body-secondary"><%= t('welcome.description') %></p>
      </div>
    </div>
  </section>

  <div class="album py-5 bg-body-tertiary">
    <div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <div class="col">
          <div class="card shadow-sm">
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
            <div class="card-body">
              <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                </div>
                <small class="text-body-secondary">9 mins</small>
              </div>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card shadow-sm">
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
            <div class="card-body">
              <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                </div>
                <small class="text-body-secondary">9 mins</small>
              </div>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card shadow-sm">
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
            <div class="card-body">
              <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                </div>
                <small class="text-body-secondary">9 mins</small>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

</main>

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>" class="col">
  <div class="card shadow-sm">
    <div class="card-body">
      <h2 class="card-text"><%= article.title %></h2>
      <p><%= @article.body %></p>
    </div>
  </div>
</div>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title, class: 'w-100'%>
  </div>
  <div>
    <%= form.label :preview_image, style: "display: block" %>
    <%= form.file_field :preview_image %>
  </div>
  <div class="field">
    <%= form.label :body %>
    <%= form.rich_text_area :body %>
  </div>
  <div class="field">
    <%= form.check_box :published_at, {}, DateTime.now, nil %>
    <%= form.label :published_at, "Published" %>
  </div>
  <div class="col-11 offset-1 d-flex justify-content-end">
    <%= form.submit :class => 'btn btn-outline-secondary' %>
  </div>
<% end %>

app/views/articles/_index_article.html.erb
<div id="<%= dom_id article %>" class="col">
  <div class="card shadow-sm">
    <% if article.preview_image.present? %>
      <%= image_tag article.preview_image, height: '225', style: 'object-fit: contain; border-radius: 15px' %>
    <% else %>
      <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false">
        <title>Placeholder</title>
        <rect width="100%" height="100%" fill="#55595c"/>
        <text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text>
      </svg>
    <% end %>
    <div class="card-body">
      <p class="card-text"><%= article.title %></p>
      <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group">
          <%= link_to t('buttons.show_article'), article, class: "btn btn-sm btn-outline-secondary me-1" %>
          <% if can? :edit, article %>
            <%= link_to t('buttons.edit'), edit_article_path(article), class: "btn btn-sm btn-outline-secondary" %>
          <% end %>
        </div>
        <% if article.published_at? %>
          <small class="text-body-secondary"><%= t('helpers.published_at') %><%= article.published_at.to_fs(:short) %></small>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h1><%= t('buttons.editing') %></h1>

<div class="col-10 offset-1 d-flex justify-content-end">
  <%= link_to t('buttons.show_article'), @article,  class: 'btn btn-outline-secondary me-1' %>
  <%= link_to t('buttons.show_all_articles'), articles_path,  class: 'btn btn-outline-secondary' %>
</div>

<div class="row">
  <div class="col-10 offset-1">
    <%= render "form", article: @article %>
  </div>
</div>

app/views/articles/index.html.erb
<div class="album py-5 bg-body-tertiary">
  <div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">


      <% @articles.each do |article| %>
        <%= render 'articles/index_article', article: article %>
      <% end %>

    </div>
  </div>
</div>

app/views/articles/new.html.erb
<h1><%= t('buttons.adding_new') %></h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/show.html.erb
<div class="row">
  <div class="col-10 offset-1 d-flex justify-content-end">
    <%= link_to t('buttons.show_all_articles'), articles_path, class: 'btn btn-outline-secondary me-1' %>
    <% if can? :edit, @article %>
      <%= link_to t('buttons.edit'), edit_article_path(@article), class: 'btn btn-outline-secondary me-1' %>
    <% end %>
    <% if can? :delete, @article %>
      <%= button_to t('buttons.delete'), @article, method: :delete, class: 'btn btn-danger px-3' %>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="col-10 offset-1">
    <%= render @article %>
  </div>
</div>

app/views/layouts/_flash_messages.html.erb
<% if notice || alert %>
  <div class="container">
    <p style="color: green" class="notice"><%= notice %></p>
    <p  style="color: green" class="alert"><%= alert %></p>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="text-body-secondary py-5">
  <div class="container">
    <p class="float-end mb-1">
      <%= link_to t('buttons.to_top'), '#', class: 'btn btn-outline-secondary' %>
    </p>
    <p class="mb-1">&COPY; <%= Date.current.year %> KavaFans. All rights reserved.</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="p-3 mb-3 border-bottom">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <%= link_to root_path do %>
        <%= image_tag("logo.svg", alt: "IHOP logo", height: "32") %>
      <% end %>

      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <%= link_to t('header.menu.news'), news_path, class: root_link_class(news_path) %>
        <%= link_to t('header.menu.cooking'), cooking_path, class: current_link_class(cooking_path) %>
        <%= link_to t('header.menu.roastering'), roastering_path, class: current_link_class(roastering_path) %>
        <%= link_to t('header.menu.other'), other_path, class: current_link_class(other_path) %>
        <%= link_to t('header.menu.about'), about_path, class: current_link_class(about_path) %>
      </ul>
      <div class="text-end">
        <% if user_signed_in? %>
          <div class="dropdown text-end d-flex">
            <div class="px-2 py-1"><b><%= current_user.nickname %></b> (<%= current_user.email %>)</div>
            <a href="#" class="d-block link-body-emphasis text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
              <img src="<%= current_user.image %>" alt="mdo" width="32" height="32" class="rounded-circle">
            </a>
            <ul class="dropdown-menu text-small">
              <li><%= link_to t('header.new_article'), new_article_path, class: "dropdown-item"%></li>
              <li><%= link_to t('devise.shared.links.profile'), edit_user_registration_path, class: 'dropdown-item' %></li>
              <li>
                <hr class="dropdown-divider">
              </li>
              <li>
                <%= button_to t('devise.sessions.sign_out'), destroy_user_session_path, class: "dropdown-item", method: :delete, form: { turbolink: false } %>
              </li>
            </ul>
          </div>

        <% else %>
          <%= link_to new_user_session_path do %>
            <button type="button" class="btn btn-outline-primary me-2"><%= t('devise.registrations.sign_in') %></button>
          <% end %>
          <%= link_to new_user_registration_path do %>
            <button type="button" class="btn btn-primary"><%= t('devise.registrations.sign_up') %></button>
          <% end %>
          <%= button_to  (image_tag("google.png", height: 38)), user_google_oauth2_omniauth_authorize_path, method: :post, :data => {turbo: "false"}, class: "btn btn-outline-primary me-2 p-0", :form_class => "d-block d-md-inline text-center" %>
      <% end %>

      </div>
    </div>
  </div>
</header>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyistAlbum</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render "layouts/header" %>
  <%= render "layouts/flash_messages" %>
  <div class="album py-5 bg-body-tertiary">
    <div class="container">
      <%= yield %>
    </div>
  </div>
  <%= render "layouts/footer" %>
  </body>
</html>